# Generated by Django 3.2.2 on 2023-04-23 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rms_app', '0007_auto_20210826_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='food_type',
            field=models.CharField(default='starter', max_length=100),
            preserve_default=False,
        ),
    ]
