# Generated by Django 3.2.2 on 2023-04-23 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rms_app', '0008_food_food_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='food_type',
            field=models.CharField(default='', max_length=100),
        ),
    ]
