# Generated by Django 3.2.2 on 2023-04-23 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rms_app', '0009_alter_food_food_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='food_availability',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='food_type',
            field=models.CharField(choices=[('None', 'None'), ('Starters', 'Starters'), ('Main Course', 'Main Course'), ('Desserts', 'Desserts'), ('Beverages', 'Beverages')], default='None', max_length=100),
        ),
    ]
