# Generated by Django 3.2.2 on 2023-04-23 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rms_app', '0010_auto_20230424_0126'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='food_source',
            field=models.CharField(choices=[('Veg', 'Veg'), ('Non-Veg', 'Non-Veg')], default='Veg', max_length=100),
        ),
        migrations.AlterField(
            model_name='food',
            name='food_availability',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=100),
        ),
    ]
